name = "Marchcraft Packwiz"
author = "TD"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69e6aed728fa8d4c608d5e3ae3418e70400bd208e27ed329adf0a4840acd0810"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
