name = "Marchcraft Packwiz"
author = "TD"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "522f1ac28d48c1718047faf3db16945e5fdacd80f6752871590435ceaae7d72f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
