name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98ccd0cd037022dce3a00104dfc8e537f87420bbd613dca29029f19162d95214"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
