name = "Marchcraft Packwiz"
author = "TD"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa3f05bb2261cf351466a71c6ddb47d86d0fcfc60dd1032af054ec910224438"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
