name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d63501d9f8fdb6bc81eddfb262c47af24ce065d9557d4385801e4b77eb330e1a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
