name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a0e2796852c710ad29c7e1171bad26f6ad366662fd34740404774eb504d6522"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
