name = "Marchcraft Packwiz"
author = "TD"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b967695c3b5cafcd5eabf00de3322c4aa536e5a669a35307930aec8f018d6b22"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
