name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fae5eba3a5fa8fecd57e11dbeaf0b11139fb68afe10027874b4c4dd17ca21b16"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
