name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1223039e45e0cbc4031ce8f5963ca57c7af2269c5b9f9d1f66e83e4c286e54b9"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
