name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cd5b4161136294cee1f5097b535a39362da112b02763ceac3208a1fa17077f5"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
