name = "Marchcraft Packwiz"
author = "TD"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ef7307d90a8e91f06047c3e9849143a42eac936ab081efffd915cf271eae12a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
